### ISSUE TITLE
unable to capture the authorization

### ISSUE THREAD

**Issue by michaelserna** [finix-payments/processing-php-client#28]
when  passing an amount to the capture method `$authorization = $authorization->capture(50);` or capturing with an amount and fee included `$authorization = $authorization->capture(50, 10);` it captures an authorizatino successfully. However, when no amount is passed it fails `$authorization = $authorization->capture();` . Let's fix this so the amount captured defaults to the total amount unless the user passes an amount 

http://developers.finixpayments.com/?shell#step-7-capture-the-authorization

**Comment by phuonghuynh** [comment]
@michaelserna @rserna2010  i think this is a new feature for client libraries, could we also need to fix this in java, python and ruby as well ?

**Comment by rserna2010** [comment]
@phuonghuynh yes they should all contain this. looking at the balanced example this was supported: https://github.com/balanced/balanced-php/blob/5710bec8991c0984afcc0aec6e4f9be545680f53/src/Balanced/CardHold.php

**Comment by rserna2010** [comment]
@phuonghuynh can we make this an array as well to be consistent with the other syntax we use in the client. 

Example:
```
$authorization = $authorization->capture(
    array(
      "capture_amount"=> 100, 
      "fee"=> 50
));
```

This helps when we make feature additions to the API, (eg adding statement_descriptor to the request)
