### ISSUE TITLE
provision merchant without passing a processor 

### ISSUE THREAD

**Issue by michaelserna** [finix-payments/processing-php-client#32]
you should be able to provision a merchant without passing a processor

http://developers.finixpayments.com/?php#provision-a-merchant43

This works:

```
$identity = Identity::retrieve('IDuKoAAfELXeFZdYGmBV1P4n');
$merchant = $identity->provisionMerchantOn(new Merchant(["processor" => "DUMMY_V1"]));
```

but code below should also work when you don't pass a processor:
```
$identity = Identity::retrieve('IDuKoAAfELXeFZdYGmBV1P4n');
$merchant = new Merchant();
$merchant = $identity->provisionMerchantOn($merchant);
```

**Comment by phuonghuynh** [comment]
@michaelserna processor is mandatory when create merchant in processing api, could you double check with the processing team?

/cc @osklyarenko @rserna2010

**Comment by rserna2010** [comment]
just clarified with @phuonghuynh it's not required.

**Comment by phuonghuynh** [comment]
This is done in https://github.com/finix-payments/processing-php-client/pull/33
